### ISSUE TITLE
UnitHealth

### ISSUE THREAD

**Issue by Technojo01** [phanx-wow/oUF_Phanx#18]
Not sure how it happened, but I've got this error since 7.1: 

`801x oUF_Phanx\Functions.lua:211: Usage: UnitHealth("unit")
[C]:: ?
oUF_Phanx\Functions.lua:211: in function <oUF_Phanx\Functions.lua:206>
(tail call): ?
oUF\events.lua:48: in function <oUF\events.lua:46>
(tail call): ?`

**Comment by Phanx** [comment]
This was already fixed in 0edf16c, and a release will be tagged as soon as I've had a chance to log in and make sure nothing else is broken.
