### ISSUE TITLE
Can't dismiss pet from unit frame menu

### ISSUE THREAD

**Issue by Technojo01** [phanx-wow/oUF_Phanx#19]
Happened on my lvl 78 hunter in Gundrak. Thanks.

`1x [ADDON_ACTION_FORBIDDEN] AddOn 'oUF_Phanx' tried to call the protected function 'CastSpellByID()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]:: in function 'CastSpellByID'
FrameXML\UnitPopup.lua:1714: in function 'func'
FrameXML\UIDropDownMenu.lua:787: in function 'UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>`

**Comment by Phanx** [comment]
Can you be more specific? What were you doing when the error occurred? If you were trying to dismiss your pet, how were you doing that? From the right-click menu on the pet frame? By clicking an action button? By pressing a key bound to a macro? (If a macro is involved, please post the actual macro as well.) Does the error occur every time you do the same thing? Does it occur when all other addons are disabled?

**Comment by Technojo01** [comment]
It was from the right-click menu on the pet frame. Will do more tests tonight but it seems to happens all the time and it is the same error every time.

**Comment by Technojo01** [comment]
Can confirm. Happens all the time using only oUF and your layout. I was in the hunter order hall.

**Comment by Infoblip** [comment]
This continues to happen with ver: 7.3.5.1 of this layout. In dalaran, went to dismiss pet and got the action forbidden error message. Had to disable to dismiss pet.

**Comment by Phanx** [comment]
Probably fixed in 29b3d23. Grab the latest Frames.lua ([link](https://github.com/phanx-wow/oUF_Phanx/raw/master/Frames.lua)), save it over the one in the addon folder, and let me know if you still get this error when attempting to dismiss your pet.
