### ISSUE TITLE
Error since 7.1

### ISSUE THREAD

**Issue by Mordread** [phanx-wow/oUF_Phanx#21]
Seems to only happen while in a party

Message: Interface\AddOns\oUF_Phanx\Functions.lua:211: Usage: UnitHealth("unit")
Time: 11/04/16 18:16:33
Count: 7
Stack: [C]: ?
Interface\AddOns\oUF_Phanx\Functions.lua:211: in function <Interface\AddOns\oUF_Phanx\Functions.lua:206>
(tail call): ?
Interface\AddOns\oUF\events.lua:48: in function <Interface\AddOns\oUF\events.lua:46>
(tail call): ?

Locals: (*temporary) = nil

**Comment by wjrogers** [comment]
I just got the same error. It was during the Holy Priest artifact quest scenario, and it may have been triggered by one of the NPCs in the scenario leaving my party.

**Comment by Phanx** [comment]
This *should* be fixed in oUF; if the release version from WoWI hasn't been updated, you can get the current development version on GitHub:

https://github.com/oUF-wow/oUF
