### ISSUE TITLE
LUA Error for Rogue Debuffs like Rupture etc.

### ISSUE THREAD

**Issue by iddno** [phanx-wow/oUF_Phanx#27]
Message: Interface\AddOns\oUF\elements\auras.lua:203: attempt to index local 'color' (a nil value)
Time: 02/11/18 23:44:20
Count: 27
Stack: Interface\AddOns\oUF\elements\auras.lua:203: attempt to index local 'color' (a nil value)
[C]: ?
Interface\AddOns\oUF\elements\auras.lua:203: in function <Interface\AddOns\oUF\elements\auras.lua:140>
Interface\AddOns\oUF\elements\auras.lua:279: in function <Interface\AddOns\oUF\elements\auras.lua:273>
Interface\AddOns\oUF\elements\auras.lua:429: in function `func'
Interface\AddOns\oUF\events.lua:50: in function <Interface\AddOns\oUF\events.lua:48>
(tail call): ?

Locals:

**Comment by Phanx** [comment]
Fixed in aa4b604
