### ISSUE TITLE
Error occurred

### ISSUE THREAD

**Issue by Infoblip** [phanx-wow/oUF_Phanx#28]
Had this issue today when in suramar with my warlock:

Message: Interface\AddOns\oUF\elements\auras.lua:203: attempt to index local 'color' (a nil value)

Stack:
Interface\AddOns\oUF\elements\auras.lua:279: in function <Interface\AddOns\oUF\elements\auras.lua:273>
Interface\AddOns\oUF\elements\auras.lua:429: in function `func'
Interface\AddOns\oUF\events.lua:50: in function <Interface\AddOns\oUF\events.lua:48>
(tail call): ?

Count: 1

Locals:
element = <unnamed> {
 0 = <userdata>
 PostCreateIcon = <function> defined @Interface\AddOns\oUF_Phanx\Functions.lua:458
 growth-y = "UP"
 createdIcons = 1
 spacing-y = 12
 size = 30
 __owner = oUFPhanxTarget {
 }
 spacing-x = 6
 anchoredIcons = 1
 PostUpdate = <function> defined @Interface\AddOns\oUF_Phanx\Functions.lua:521
 showType = true
 1 = oUFPhanxTarget.DebuffsButton1 {
 }
 PostUpdateIcon = <function> defined @Interface\AddOns\oUF_Phanx\Functions.lua:513
 visibleDebuffs = 0
 ForceUpdate = <function> defined @Interface\AddOns\oUF\elements\auras.lua:471
 initialAnchor = "BOTTOMLEFT"
 CustomFilter = <function> defined @Interface\AddOns\oUF_Phanx\Auras.lua:833
 growth-x = "RIGHT"
 num = 18
}
unit = "target"
filter = "HARMFUL"
limit = 18
isDebuff = true
offset = 0
dontHide = nil
index = 1
visible = 0
hidden = 0
updateIcon = <function> defined @Interface\AddOns\oUF\elements\auras.lua:140
VISIBLE = 1
HIDDEN = 0

**Comment by Phanx** [comment]
See #27
