### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by Infoblip** [phanx-wow/oUF_Phanx#29]
Version: 7.3.5.1
En-US
When logging in any character I get this error: 
Message: Interface\AddOns\oUF_Phanx\Elements\DispelHighlight.lua:34: DispelHighlight element requires LibDispellable-1.0

Stack:
Interface\AddOns\oUF_Phanx\Elements\DispelHighlight.lua:34: in main chunk

Count: 1

Locals:
_ = "oUF_Phanx"
ns = <table> {
}
oUF = <table> {
 DisableBlizzard = <function> defined @Interface\AddOns\oUF\blizzard.lua:59
 SetActiveStyle = <function> defined @Interface\AddOns\oUF\ouf.lua:400
 EnableFactory = <function> defined @Interface\AddOns\oUF\factory.lua:50
 HCYColorGradient = <function> defined @Interface\AddOns\oUF\colors.lua:221
 ColorGradient = <function> defined @Interface\AddOns\oUF\colors.lua:256
 SpawnHeader = <function> defined @Interface\AddOns\oUF\ouf.lua:599
 RegisterStyle = <function> defined @Interface\AddOns\oUF\ouf.lua:384
 AddElement = <function> defined @Interface\AddOns\oUF\ouf.lua:847
 useHCYColorGradient = false
 RGBToHCY = <function> defined @Interface\AddOns\oUF\colors.lua:150
 Factory = <function> defined @Interface\AddOns\oUF\factory.lua:34
 RGBColorGradient = <function> defined @Interface\AddOns\oUF\colors.lua:128
 SpawnNamePlates = <function> defined @Interface\AddOns\oUF\ouf.lua:751
 Tags = <table> {
 }
 colors = <table> {
 }
 HCYtoRGB = <function> defined @Interface\AddOns\oUF\colors.lua:176
 headers = <table> {
 }
 DisableFactory = <function> defined @Interface\AddOns\oUF\factory.lua:59
 objects = <table> {
 }
 RunFactoryQueue = <function> defined @Interface\AddOns\oUF\factory.lua:69
 RegisterInitCallback = <function> defined @Interface\AddOns\oUF\ouf.lua:355
 RegisterMetaFunction = <function> defined @Interface\AddOns\oUF\ouf.lua:366
 HandleUnit = <function> defined @Interface\AddOns\oUF\units.lua:8
 version = "7.0.14"
 IterateStyles = <function> defined @Interface\AddOns\oUF\ouf.lua:418
 Spawn = <function> defined @Interface\AddOns\oUF\ouf.lua:723
}
LibDispellable = nil

**Comment by Phanx** [comment]
Well that's a nice screwup by the packager... that code is clearly not in the tag it should have been packaging. -_-

https://github.com/phanx-wow/oUF_Phanx/blob/7.3.5.1/Elements/DispelHighlight.lua

Repackaging now.
